//! The committed `local/*/*.toml` files load, and say what the compose file,
//! the chain seeding and `local/keys.sh` beside them assume they say.
//!
//! `local/`'s configs are committed rather than generated, for the reason ADR
//! 0009 gives: a config nobody reads is a config nobody reviews. The cost of
//! that choice is drift -- a renamed compose service, a moved mount path, or a
//! settlement address that quietly stops matching what the chain actually
//! holds, none of which the TOML alone can notice. `devnet_configs_load.rs`
//! holds the fleet configs to exactly this standard; these are the local ones,
//! and they are cheaper to check because everything they name is
//! deterministic.
//!
//! **Every channel is an x402 channel, and no local config names one** (ADR
//! 0075, issue #1383). A peering is two one-way `batch-settlement` channels,
//! each opened by its own payer, and it is established from a URL by a signed
//! `POST /peers` on each end (ADR 0058 as 0075 decision 4 amends it) -- so no
//! committed file here holds a `[[peers]]`, `[[peer_channels]]` or
//! `[[pay_channels]]` row. What each peering costs lives in `local/keys.sh`'s
//! topology table instead (its `fee`, its cap, and the forwarding route's
//! `price`), because that script makes the writes. So the multi-file drift this
//! test has always caught -- a figure that must agree across two or three
//! files, and fails at run time as a refused or short payment rather than as a
//! refused config -- now spans the configs, that table and the rehearsal, and
//! [`topology`] is how this file reads the table.
//!
//! What is substituted, and only this: the key files (real key material is
//! never committed -- `local/keys.sh` writes it into a gitignored directory at
//! run time), `state_dir` and `client_edge_addr` (container paths and fixed
//! ports that no test host can supply). Every other line is the literal
//! committed content.

use std::collections::BTreeSet;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use connector_config::{Config, PeerExposure, SettlementChain, SettlementConfig, TransportPolicy};
use connector_domain::{amount_after_rate_and_fee, AssetId, Price};
use connector_runtime::SharedRateTable;
use connector_settlement_solana::test_support::LOCAL_TEST_PROGRAM_ID;

const SOLO_CONFIG: &str = include_str!("../../../local/solo/connector.toml");
const SOLO_COMPOSE: &str = include_str!("../../../local/solo/compose.yml");

const TWO_HOP_A: &str = include_str!("../../../local/two-hop/connector-a.toml");
const TWO_HOP_B: &str = include_str!("../../../local/two-hop/connector-b.toml");
const TWO_HOP_COMPOSE: &str = include_str!("../../../local/two-hop/compose.yml");

const MIXED_A: &str = include_str!("../../../local/mixed-chain/connector-a.toml");
const MIXED_B: &str = include_str!("../../../local/mixed-chain/connector-b.toml");
const MIXED_C: &str = include_str!("../../../local/mixed-chain/connector-c.toml");
const MIXED_COMPOSE: &str = include_str!("../../../local/mixed-chain/compose.yml");

const DEALING_A: &str = include_str!("../../../local/dealing/connector-a.toml");
const DEALING_B: &str = include_str!("../../../local/dealing/connector-b.toml");
const DEALING_C: &str = include_str!("../../../local/dealing/connector-c.toml");
const DEALING_COMPOSE: &str = include_str!("../../../local/dealing/compose.yml");

const ONION_A: &str = include_str!("../../../local/onion/connector-a.toml");
const ONION_B: &str = include_str!("../../../local/onion/connector-b.toml");
const ONION_COMPOSE: &str = include_str!("../../../local/onion/compose.yml");

/// The client-edge topology over the same overlay, run by its own `run.sh`
/// rather than by `LOCAL_TOPOLOGY` (it needs `toon-client` built). Still a
/// committed config on the local chain, so it is held to the same chain facts.
const ANYONE_CONFIG: &str = include_str!("../../../local/anyone/connector.toml");

/// The two `anon` configuration files. Committed because they hold no secret
/// -- each hidden-service KEY is generated by its daemon into a named volume
/// and never touches this repository.
const ONION_ANONRC_A: &str = include_str!("../../../local/onion/anonrc-a");
const ONION_ANONRC_B: &str = include_str!("../../../local/onion/anonrc-b");

/// The `anon` sidecar's image, BUILT here rather than pulled: ghcr publishes
/// none for the release whose hidden-service TLD is `.anyone` (issue #1284).
const ANON_IMAGE_DOCKERFILE: &str = include_str!("../../../local/anon-image/Dockerfile");

/// The daemon release both hidden-service topologies pin, and the TLD it
/// writes.
const ANON_VERSION: &str = "v0.4.10.2";
const ANON_TLD: &str = ".anyone";

/// The addresses each onion connector is pinned to on its own network, and
/// the targets its sidecar publishes the hidden service at. One fact in two
/// files each, because `anon` resolves that target when it PARSES its config.
const ONION_A_ADDR: &str = "172.29.0.10";
const ONION_B_ADDR: &str = "172.31.0.10";

/// The placeholders the committed onion configs carry where each daemon's
/// address goes. They still end in a hidden-service suffix, so the committed
/// files load through the real parser.
const ONION_PLACEHOLDER_A: &str = "placeholderplaceholderplaceholderplaceholderplaceholdera.anyone";
const ONION_PLACEHOLDER_B: &str = "placeholderplaceholderplaceholderplaceholderplaceholderb.anyone";

const LOCAL_README: &str = include_str!("../../../local/README.md");
const LOCAL_TOPOLOGIES_WORKFLOW: &str =
    include_str!("../../../.github/workflows/local-topologies.yml");

/// The provisioning script, read for its topology table (see [`topology`])
/// and for the shape of the writes its `channels` stage makes.
const KEYS_SCRIPT: &str = include_str!("../../../local/keys.sh");

/// What every peered topology's `sender` sources: the chain reads and the
/// journal read, written once.
const REHEARSAL: &str = include_str!("../../../local/rehearsal.sh");

/// The chain compose every topology here is merged ON TOP OF, the scripts its
/// two chain services run, and the Makefile that merges them.
const ROOT_COMPOSE: &str = include_str!("../../../docker-compose.yml");
const ANVIL_ENTRYPOINT: &str = include_str!("../../../infra/anvil/entrypoint.sh");
const ANVIL_SEED: &str = include_str!("../../../infra/anvil/seed.sh");
const SOLANA_ENTRYPOINT: &str = include_str!("../../../infra/solana/entrypoint.sh");
const MAKEFILE: &str = include_str!("../../../Makefile");

/// The revisions `packages/contracts/lib` is pinned to, as `forge` itself
/// records them (issue #1121).
const FOUNDRY_LOCK: &str = include_str!("../../../packages/contracts/foundry.lock");

/// Every committed config under `local/` that `LOCAL_TOPOLOGY` runs, with the
/// path a failure should name. Written out rather than globbed so a new
/// topology that forgets its own test still has to touch this list.
const EVERY_CONFIG: &[(&str, &str)] = &[
    ("local/solo/connector.toml", SOLO_CONFIG),
    ("local/two-hop/connector-a.toml", TWO_HOP_A),
    ("local/two-hop/connector-b.toml", TWO_HOP_B),
    ("local/mixed-chain/connector-a.toml", MIXED_A),
    ("local/mixed-chain/connector-b.toml", MIXED_B),
    ("local/mixed-chain/connector-c.toml", MIXED_C),
    ("local/dealing/connector-a.toml", DEALING_A),
    ("local/dealing/connector-b.toml", DEALING_B),
    ("local/dealing/connector-c.toml", DEALING_C),
    ("local/onion/connector-a.toml", ONION_A),
    ("local/onion/connector-b.toml", ONION_B),
];

/// One committed node config: its compose service name and its text.
type NodeConfig = (&'static str, &'static str);

/// Every topology `LOCAL_TOPOLOGY` names, with its compose file and the
/// config of each node, in `local/keys.sh`'s own node order.
const TOPOLOGIES: &[(&str, &str, &[NodeConfig])] = &[
    ("solo", SOLO_COMPOSE, &[("connector", SOLO_CONFIG)]),
    (
        "two-hop",
        TWO_HOP_COMPOSE,
        &[("connector-a", TWO_HOP_A), ("connector-b", TWO_HOP_B)],
    ),
    (
        "mixed-chain",
        MIXED_COMPOSE,
        &[
            ("connector-a", MIXED_A),
            ("connector-b", MIXED_B),
            ("connector-c", MIXED_C),
        ],
    ),
    (
        "onion",
        ONION_COMPOSE,
        &[("connector-a", ONION_A), ("connector-b", ONION_B)],
    ),
    (
        "dealing",
        DEALING_COMPOSE,
        &[
            ("connector-a", DEALING_A),
            ("connector-b", DEALING_B),
            ("connector-c", DEALING_C),
        ],
    ),
];

// ─── loading a committed config ──────────────────────────────────────────────

/// A file holding `contents`, kept alive by the returned handle.
fn file_with(dir: &Path, name: &str, contents: &str) -> PathBuf {
    let path = dir.join(name);
    let mut handle = std::fs::File::create(&path).expect("create sandbox file");
    handle
        .write_all(contents.as_bytes())
        .expect("write sandbox file");
    path
}

/// `raw` with its one top-level `key = "committed"` line -- however the `=` is
/// aligned -- set to `key = "value"`, refusing a file that does not commit
/// exactly that value: a renamed line must fail here rather than let the
/// substitution silently do nothing.
fn replace_setting(raw: &str, key: &str, committed: &str, value: &str) -> String {
    let mut found = 0;
    let out: Vec<String> = raw
        .lines()
        .map(|line| {
            let setting = line
                .strip_prefix(key)
                .map(str::trim_start)
                .and_then(|rest| rest.strip_prefix('='))
                .map(str::trim);
            if setting == Some(&format!("\"{committed}\"")) {
                found += 1;
                format!("{key} = \"{value}\"")
            } else {
                line.to_owned()
            }
        })
        .collect();
    assert_eq!(
        found, 1,
        "expected exactly one `{key} = \"{committed}\"` in the committed config -- if that line \
         was renamed, update this test rather than letting the substitution silently do nothing"
    );
    out.join("\n")
}

/// Every `/app/data/...` path a committed config names, found by scanning the
/// text rather than by listing them here, so a new key file cannot be missed:
/// [`loadable`] refuses to return a string that still names a container path.
fn container_paths(raw: &str) -> BTreeSet<&str> {
    let mut found = BTreeSet::new();
    for (index, _) in raw.match_indices("\"/app/data/") {
        let quoted = &raw[index + 1..];
        let end = quoted.find('"').expect("a quoted path is closed");
        found.insert(&quoted[..end]);
    }
    found
}

/// The committed text with only the unsupplyable lines swapped out.
fn loadable(raw: &str, dir: &Path) -> String {
    let key = file_with(
        dir,
        "key",
        "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    );
    let bearer = file_with(dir, "bearer", "a-sandbox-token");
    let allowlist = file_with(
        dir,
        "allowlist",
        "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef\n",
    );
    let state = dir.join("state");
    std::fs::create_dir_all(&state).expect("create sandbox state dir");

    let mut out = raw.to_string();
    for path in container_paths(raw) {
        let name = path.rsplit('/').next().expect("a path has a last segment");
        let substitute = match name {
            "operator-bearer-token" => &bearer,
            "operator-write-keys" => &allowlist,
            other if other.ends_with(".key") => &key,
            other => panic!(
                "no sandbox stand-in for the container file `{other}`. Add one here -- a config \
                 that names a file this test cannot supply cannot be checked at all."
            ),
        };
        out = out.replace(path, &substitute.display().to_string());
    }
    out = replace_setting(
        &out,
        "state_dir",
        "/app/state",
        &state.display().to_string(),
    );
    out = replace_setting(&out, "client_edge_addr", "0.0.0.0:3000", "127.0.0.1:0");
    for line in out.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        assert!(
            !line.contains("/app/"),
            "`{line}` still names a container path, so whatever loads below is not what this \
             test thinks it is checking"
        );
    }
    out
}

/// Load one committed config in a sandbox of its own.
fn load(name: &str, raw: &str) -> Config {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = file_with(dir.path(), "connector.toml", &loadable(raw, dir.path()));
    Config::load(&path).unwrap_or_else(|error| panic!("{name} must load: {error}"))
}

/// The one figure a price this topology requires to be **flat** charges.
/// None of the committed local topologies prices by size, and a topology
/// that gains a schedule has to teach these assertions the slope half of ADR
/// 0028's path invariant rather than route around this.
fn flat(price: Price) -> u64 {
    assert!(
        price.is_flat(),
        "this topology's committed price carries a slope ({price}), and the ADR 0028 path \
         arithmetic in this file compares one figure per hop"
    );
    price.base()
}

/// The lines of a file that are not comments -- what a script or compose file
/// DOES, as opposed to what its prose says it used to do.
fn executable_lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
}

/// The non-comment lines of a file, joined: what a positive "the script DOES
/// this" check must search, so that a line surviving only in prose cannot
/// satisfy it.
fn code(text: &str) -> String {
    executable_lines(text).collect::<Vec<_>>().join("\n")
}

// ─── local/keys.sh's topology table ──────────────────────────────────────────

/// One node of a topology, as `local/keys.sh` provisions it.
#[derive(Debug)]
struct TableNode {
    name: String,
    evm_index: u32,
    solana_index: u32,
    /// The host port compose publishes the node's client edge on, where the
    /// `channels` stage writes to it; `None` for a node with no host port.
    port: Option<u16>,
}

/// One peering: `payer` opens and funds its channel toward `payee`, and
/// retains `fee` per packet it carries over it.
#[derive(Debug)]
struct TablePeering {
    id: String,
    chain: SettlementChain,
    payer: String,
    payee: String,
    fee: u64,
    /// `0` keeps `DEFAULT_MAX_PACKET_AMOUNT`.
    max_packet_amount: u64,
}

/// One forwarding route `POST /routes/peers` writes on `node`.
#[derive(Debug)]
struct TableRoute {
    node: String,
    prefix: String,
    peer_id: String,
    price: u64,
}

#[derive(Debug)]
struct Topology {
    nodes: Vec<TableNode>,
    peerings: Vec<TablePeering>,
    routes: Vec<TableRoute>,
}

impl Topology {
    fn peering(&self, id: &str) -> &TablePeering {
        self.peerings
            .iter()
            .find(|peering| peering.id == id)
            .unwrap_or_else(|| panic!("local/keys.sh's table has no '{id}' peering"))
    }

    fn route_on(&self, node: &str) -> &TableRoute {
        let routes: Vec<&TableRoute> = self.routes.iter().filter(|r| r.node == node).collect();
        assert_eq!(
            routes.len(),
            1,
            "expected exactly one forwarding route on {node} in local/keys.sh's table"
        );
        routes[0]
    }
}

/// `local/keys.sh`'s table entry for `name`: the `  name)` arm of its
/// topology `case`, up to its `;;`. The table is the peering half of every
/// topology's arithmetic, so it is parsed rather than restated here.
fn topology(name: &str) -> Topology {
    let head = format!("\n  {name})\n");
    let arm = KEYS_SCRIPT
        .split_once(&head)
        .unwrap_or_else(|| panic!("local/keys.sh has no `{name})` arm in its topology table"))
        .1
        .split_once("\n    ;;")
        .expect("a case arm ends in ;;")
        .0;
    let field = |key: &str| -> Vec<String> {
        arm.lines()
            .map(str::trim)
            .find_map(|line| line.strip_prefix(&format!("{key}=\"")))
            .map(|rest| {
                rest.trim_end_matches('"')
                    .split_whitespace()
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default()
    };
    let number = |value: &str, what: &str| -> u64 {
        value
            .parse()
            .unwrap_or_else(|_| panic!("local/keys.sh's {name} {what} is `{value}`"))
    };

    let nodes = field("NODES")
        .iter()
        .map(|entry| {
            let parts: Vec<&str> = entry.split(':').collect();
            assert_eq!(
                parts.len(),
                4,
                "a NODES entry is node:evm:solana:port, got {entry}"
            );
            TableNode {
                name: parts[0].to_owned(),
                evm_index: number(parts[1], "evm index") as u32,
                solana_index: number(parts[2], "solana index") as u32,
                port: (parts[3] != "-").then(|| number(parts[3], "port") as u16),
            }
        })
        .collect();
    let peerings = field("PEERINGS")
        .iter()
        .map(|entry| {
            let parts: Vec<&str> = entry.split(':').collect();
            assert_eq!(
                parts.len(),
                6,
                "a PEERINGS entry is id:chain:payer:payee:fee:max_packet_amount, got {entry}"
            );
            TablePeering {
                id: parts[0].to_owned(),
                chain: match parts[1] {
                    "evm" => SettlementChain::Evm,
                    "solana" => SettlementChain::Solana,
                    other => panic!("local/keys.sh names an unknown chain `{other}`"),
                },
                payer: parts[2].to_owned(),
                payee: parts[3].to_owned(),
                fee: number(parts[4], "fee"),
                max_packet_amount: number(parts[5], "max_packet_amount"),
            }
        })
        .collect();
    let routes = field("ROUTES")
        .iter()
        .map(|entry| {
            let parts: Vec<&str> = entry.split(':').collect();
            assert_eq!(
                parts.len(),
                4,
                "a ROUTES entry is node:prefix:peer:price, got {entry}"
            );
            TableRoute {
                node: parts[0].to_owned(),
                prefix: parts[1].to_owned(),
                peer_id: parts[2].to_owned(),
                price: number(parts[3], "route price"),
            }
        })
        .collect();
    Topology {
        nodes,
        peerings,
        routes,
    }
}

/// The value of a bare `NAME=value` assignment in a script, as an integer.
fn script_constant(script: &str, file: &str, name: &str) -> u128 {
    let needle = format!("\n{name}=");
    let value = script
        .split_once(&needle)
        .unwrap_or_else(|| panic!("{file} no longer defines `{name}` at the start of a line"))
        .1
        .lines()
        .next()
        .expect("an assignment has a line")
        .trim();
    value
        .parse()
        .unwrap_or_else(|_| panic!("{file}'s {name} is `{value}`, not an integer"))
}

fn keys_script_constant(name: &str) -> u128 {
    script_constant(KEYS_SCRIPT, "local/keys.sh", name)
}

/// The value of a bare `NAME=value` assignment in a script, as text.
fn script_word<'a>(script: &'a str, file: &str, name: &str) -> &'a str {
    script
        .split_once(&format!("\n{name}="))
        .unwrap_or_else(|| panic!("{file} no longer defines `{name}` at the start of a line"))
        .1
        .lines()
        .next()
        .expect("an assignment has a line")
        .trim()
}

/// `0x` + lowercase hex, the spelling every comparison of an EVM address here
/// uses: EIP-55 checksum casing is presentation.
fn hex20(address: [u8; 20]) -> String {
    format!("0x{}", hex::encode(address))
}

fn settlement(config: &Config, chain: SettlementChain) -> &SettlementConfig {
    config
        .settlements()
        .iter()
        .find(|settlement| settlement.chain() == chain)
        .unwrap_or_else(|| panic!("this node holds no {chain:?} settlement table"))
}

// ─── every config ────────────────────────────────────────────────────────────

/// **No local config holds a TOON channel row, or any peering row at all**
/// (ADR 0075 decision 13, issue #1383).
///
/// A peering is established from a URL by a signed `POST /peers` on each end,
/// which opens that node's own outbound x402 channel and binds the other's by
/// the voucher signer its self-description publishes. There is no channel id
/// to paste anywhere, so a `[[peer_channels]]`/`[[pay_channels]]` row here
/// would be a TOON channel, and a `[[peers]]` row a config-declared peering --
/// which still proves itself with a `toon-channel` claim until #1380. Both
/// shapes still PARSE (#1380 refuses them by name); this is what keeps
/// `local/` off them in the meantime.
#[test]
fn every_local_config_loads_and_holds_no_toon_channel_row() {
    for (name, raw) in EVERY_CONFIG
        .iter()
        .copied()
        .chain([("local/anyone/connector.toml", ANYONE_CONFIG)])
    {
        let config = load(name, raw);
        assert!(
            config.peers().is_empty(),
            "{name} declares a [[peers]] row. Every local peering is a runtime one, written by \
             local/keys.sh's `channels` stage with `POST /peers`; a config-declared peering still \
             proves itself with a toon-channel claim (#1380)."
        );
        assert!(
            config.peer_channels().is_empty() && config.pay_channels().is_empty(),
            "{name} names a channel in [[peer_channels]] or [[pay_channels]] -- a TOON channel, \
             which no local chain opens any more (ADR 0075)"
        );
        assert!(
            config.client_channels().is_empty(),
            "{name} declares a [[client_channels]] row -- a TOON channel by construction"
        );
        assert!(
            config.peer_routes().is_empty(),
            "{name} writes a forwarding `[[routes]]` row. A forward names a peering, and every \
             local peering is a runtime one, so its route is `POST /routes/peers` in \
             local/keys.sh's table"
        );
        for line in executable_lines(raw) {
            for header in ["[[peers]]", "[[peer_channels]]", "[[pay_channels]]"] {
                assert_ne!(line, header, "{name} still carries a `{header}` table");
            }
        }
    }
}

/// **Every settlement table is an x402 one, on the chain `infra/` seeds** (ADR
/// 0075 decision 13).
///
/// The EVM token is the FiatToken `infra/anvil/seed.sh` deploys, under its own
/// EIP-712 domain ("USDC", "2"); the Solana table carries the sponsor minimum
/// that makes this node an x402 receiver. The two TOON facts left --
/// `contract_address` and `program_id` -- are what the connector still BOOTS
/// through until #1385, and must name exactly the registry and program the
/// chains still carry for that and nothing else.
#[test]
fn every_local_settlement_table_is_an_x402_one_on_the_seeded_chain() {
    let usdc = script_word(ANVIL_SEED, "infra/anvil/seed.sh", "USDC").to_lowercase();
    let registry =
        script_word(ANVIL_SEED, "infra/anvil/seed.sh", "TOKEN_NETWORK_REGISTRY").to_lowercase();
    for (name, raw) in EVERY_CONFIG
        .iter()
        .copied()
        .chain([("local/anyone/connector.toml", ANYONE_CONFIG)])
    {
        let config = load(name, raw);
        for table in config.settlements() {
            match table {
                SettlementConfig::Evm(evm) => {
                    assert_eq!(evm.rpc_url(), "http://anvil:8545", "{name}");
                    assert_eq!(
                        hex20(evm.token_address()),
                        usdc,
                        "{name}'s EVM token must be the FiatToken infra/anvil/seed.sh deploys"
                    );
                    assert_eq!(evm.decimals(), 6, "{name}: FiatToken v2.2 has 6 decimals");
                    assert_eq!(
                        hex20(evm.contract_address()),
                        registry,
                        "{name}'s contract_address must be the boot-only TokenNetworkRegistry \
                         infra/anvil/seed.sh deploys (until #1385)"
                    );
                    let batch = evm.batch_settlement().unwrap_or_else(|| {
                        panic!("{name} settles on EVM without [settlement.evm.batch_settlement]")
                    });
                    assert_eq!(
                        (batch.asset_eip712_name(), batch.asset_eip712_version()),
                        ("USDC", "2"),
                        "{name}: the FiatToken's own EIP-712 domain, which its ERC-3009 \
                         authorisation is signed under"
                    );
                }
                SettlementConfig::Solana(solana) => {
                    assert_eq!(solana.rpc_url(), "http://solana-validator:8899", "{name}");
                    assert_eq!(
                        solana.program_id(),
                        LOCAL_TEST_PROGRAM_ID,
                        "{name}: the boot-only program infra/solana/entrypoint.sh still loads"
                    );
                    assert!(
                        solana.batch_settlement().is_some(),
                        "{name} settles on Solana without [settlement.solana.batch_settlement]"
                    );
                }
            }
        }
    }
}

/// No credential may be written literally into a committed config.
#[test]
fn no_local_config_carries_a_literal_credential() {
    for (name, raw) in EVERY_CONFIG {
        for field in ["bearer_token", "write_keys", "secret"] {
            for line in raw.lines() {
                let line = line.trim();
                if line.starts_with('#') {
                    continue;
                }
                let Some((left, _)) = line.split_once('=') else {
                    continue;
                };
                assert_ne!(
                    left.trim(),
                    field,
                    "{name} sets `{field}` literally. Credentials are named by path \
                     (`{field}_file`) and written by local/keys.sh -- never committed."
                );
            }
        }
    }
}

// ─── the chains every topology runs on ───────────────────────────────────────

/// **anvil hosts x402 at the addresses the binary binds, and Circle's
/// FiatToken as USDC** (ADR 0075 decision 13).
///
/// The connector binds `x402BatchSettlement` and its collectors as constants
/// of the binary, so `infra/anvil/seed.sh` placing them anywhere else would
/// boot every node and open no channel. And no TOON contract is deployed
/// beyond the one registry the connector still boots through (#1385): no
/// `MockERC20`, no forwarder, no `RollingSwapChannel`, and no `forge` at all.
#[test]
fn the_local_anvil_places_x402_where_the_binary_binds_it() {
    let seed = |name: &str| script_word(ANVIL_SEED, "infra/anvil/seed.sh", name).to_lowercase();
    assert_eq!(
        seed("X402_BATCH_SETTLEMENT"),
        hex20(connector_signer::X402_BATCH_SETTLEMENT_ADDRESS)
    );
    assert_eq!(
        seed("ERC3009_DEPOSIT_COLLECTOR"),
        hex20(connector_settlement_evm::ERC3009_DEPOSIT_COLLECTOR_ADDRESS)
    );
    assert_eq!(
        seed("PERMIT2_DEPOSIT_COLLECTOR"),
        hex20(connector_settlement_evm::PERMIT2_DEPOSIT_COLLECTOR_ADDRESS)
    );
    assert_eq!(
        seed("PERMIT2"),
        hex20(connector_settlement_evm::PERMIT2_ADDRESS)
    );
    for file in [
        "SignatureChecker.runtime.hex",
        "x402BatchSettlement.runtime.hex",
        "ERC3009DepositCollector.runtime.hex",
        "Permit2DepositCollector.runtime.hex",
        "Permit2.runtime.hex",
        "FiatTokenV2_2.creation.hex",
        "FiatTokenProxy.creation.hex",
    ] {
        assert!(
            code(ANVIL_SEED).contains(&format!("$X402/{file}")),
            "infra/anvil/seed.sh must place {file} from the committed bytecode the tier-3 tests \
             place (`X402Chain::place`)"
        );
    }
    assert!(
        code(ANVIL_SEED).contains("'configureMinter(address,uint256)'"),
        "USDC is MINTED ON DEMAND: the seed must make a genesis account the token's minter, \
         which is what local/keys.sh mints each node's USDC from"
    );
    assert_eq!(
        script_word(KEYS_SCRIPT, "local/keys.sh", "USDC").to_lowercase(),
        seed("USDC"),
        "local/keys.sh mints the token the seed deploys"
    );
    assert_eq!(
        script_word(KEYS_SCRIPT, "local/keys.sh", "X402_BATCH_SETTLEMENT").to_lowercase(),
        seed("X402_BATCH_SETTLEMENT"),
        "local/keys.sh reads every EVM channel back off the contract the seed placed"
    );

    for (file, text) in [
        ("infra/anvil/seed.sh", ANVIL_SEED),
        ("infra/anvil/entrypoint.sh", ANVIL_ENTRYPOINT),
        ("docker-compose.yml", ROOT_COMPOSE),
    ] {
        for line in executable_lines(text) {
            for gone in [
                "DeployLocal",
                "MockERC20",
                "RollingSwapChannel",
                "forge ",
                "packages/contracts",
            ] {
                assert!(
                    !line.contains(gone),
                    "{file} still runs `{gone}`: `{line}`. The local chain carries no TOON \
                     deployment but the boot-only registry (ADR 0075, #1383)."
                );
            }
        }
    }

    // The healthcheck waits on the LAST thing the seed creates, under
    // `set -e`, so code there means every step before it landed.
    let token_network = script_word(ANVIL_SEED, "infra/anvil/seed.sh", "TOKEN_NETWORK");
    assert!(
        ROOT_COMPOSE.contains(&format!("cast code {token_network} ")),
        "docker-compose.yml's anvil healthcheck must wait on {token_network}, the last contract \
         infra/anvil/seed.sh creates"
    );
    assert!(
        code(ANVIL_ENTRYPOINT).contains("sh -eu /anvil/seed.sh"),
        "the seed runs as its own `sh -eu` process, where `set -e` holds -- inside the \
         entrypoint's `if` it would not, and a failed step would be skipped silently"
    );
    for mount in [
        "./infra/anvil:/anvil:ro",
        "./crates/connector-settlement-evm/contracts:/evm:ro",
    ] {
        assert!(
            ROOT_COMPOSE.contains(mount),
            "docker-compose.yml's anvil service must mount `{mount}` -- read-only: it compiles \
             nothing and writes nothing a developer owns"
        );
    }
}

/// **The validator loads `payment-channels` and p-token from the pinned
/// fixtures** (ADR 0075 decision 13): the same hash-checked dumps
/// `SolanaValidator::spawn` loads, mounted rather than copied.
#[test]
fn the_local_validator_loads_payment_channels_and_p_token_from_the_pinned_fixtures() {
    use connector_settlement_solana::batch::wire::PAYMENT_CHANNELS_PROGRAM_ID;

    assert!(
        code(SOLANA_ENTRYPOINT).contains(&format!(
            "PAYMENT_CHANNELS_ID={PAYMENT_CHANNELS_PROGRAM_ID}"
        )),
        "infra/solana/entrypoint.sh must load payment-channels at {PAYMENT_CHANNELS_PROGRAM_ID}, \
         the program id the binary binds every Solana channel to"
    );
    assert!(
        code(SOLANA_ENTRYPOINT).contains(&format!("SPL_TOKEN={}", spl_token::id())),
        "and p-token at the SPL Token id, where the bundled SPL Token refuses the `Batch` a \
         two-payout `distribute` sends (#1358)"
    );
    for fixture in ["/fixtures/payment_channels.so", "/fixtures/p_token.so"] {
        assert!(
            code(SOLANA_ENTRYPOINT).contains(fixture),
            "infra/solana/entrypoint.sh must load {fixture}"
        );
    }
    assert!(
        ROOT_COMPOSE.contains("./crates/connector-settlement-solana/fixtures:/fixtures:ro"),
        "the fixtures are MOUNTED from where the harness pins their hashes, never copied: a \
         second copy is a second program to drift"
    );
    assert!(
        code(SOLANA_ENTRYPOINT).contains(LOCAL_TEST_PROGRAM_ID),
        "TOON's own program is still loaded at {LOCAL_TEST_PROGRAM_ID} while the connector boots \
         through `[settlement.solana] program_id` (#1385)"
    );
}

// ─── every topology ──────────────────────────────────────────────────────────

/// `local/keys.sh`'s table, the compose file and the Makefile agree about
/// every topology's nodes: the same services, each node's committed config
/// and key directory mounted, and every host port the `channels` stage writes
/// to actually published.
#[test]
fn every_topology_table_agrees_with_its_compose_file_and_the_makefile() {
    let mut evm_indices = BTreeSet::new();
    let mut solana_indices = BTreeSet::new();
    for (name, compose, configs) in TOPOLOGIES {
        let table = topology(name);
        let nodes: Vec<&str> = table.nodes.iter().map(|node| node.name.as_str()).collect();
        let committed: Vec<&str> = configs.iter().map(|(node, _)| *node).collect();
        assert_eq!(
            nodes, committed,
            "local/keys.sh provisions {name}'s nodes from its table, never discovered"
        );
        assert!(
            MAKEFILE.contains(&format!("LOCAL_NODES_{name} := {}", nodes.join(" "))),
            "the Makefile must start exactly {name}'s connectors"
        );
        for node in &table.nodes {
            assert!(
                evm_indices.insert(node.evm_index) && solana_indices.insert(node.solana_index),
                "{name}'s {} reuses a settlement index another node already holds",
                node.name
            );
            assert!(
                compose.contains(&format!("./local/.keys/{name}/{}:/app/data:ro", node.name)),
                "local/{name}/compose.yml must mount {}'s key directory",
                node.name
            );
            match node.port {
                Some(port) => assert!(
                    compose.contains(&format!("'127.0.0.1:{port}:3000'")),
                    "local/{name}/compose.yml must publish {}'s client edge on {port}, where \
                     local/keys.sh's `channels` stage writes to it",
                    node.name
                ),
                None => assert_eq!(
                    (*name, node.name.as_str()),
                    ("onion", "connector-b"),
                    "only onion's B has no host port -- its only door is the circuit"
                ),
            }
        }
    }
    assert!(
        evm_indices.is_disjoint(&solana_indices),
        "EVM and Solana indices must be disjoint, so no 32 bytes is ever used on both curves"
    );
}

/// **Every peered node publishes itself and can be written to.** A peering is
/// established from BOTH ends (ADR 0075 decision 4), so each node of each
/// peering needs a `[node]` self-description at the URL the other reaches it
/// by, an operator surface for `POST /peers`, and a settlement table on the
/// peering's chain with the x402 half of the port turned on.
#[test]
fn every_peered_node_publishes_itself_and_can_be_written_to() {
    for (name, _compose, configs) in TOPOLOGIES {
        let table = topology(name);
        for peering in &table.peerings {
            for node in [&peering.payer, &peering.payee] {
                let raw = configs
                    .iter()
                    .find(|(candidate, _)| candidate == node)
                    .unwrap_or_else(|| panic!("{name} has no config for {node}"))
                    .1;
                let file = format!("local/{name}/{node}.toml");
                let config = load(&file, raw);
                let published = config
                    .node()
                    .and_then(|node| node.http_endpoint())
                    .unwrap_or_else(|| panic!("{file} publishes no [node] http_endpoint"));
                let expected = if *name == "onion" {
                    let placeholder = if node == "connector-a" {
                        ONION_PLACEHOLDER_A
                    } else {
                        ONION_PLACEHOLDER_B
                    };
                    format!("http://{placeholder}/ilp")
                } else {
                    format!("http://{node}:3000/ilp")
                };
                assert_eq!(
                    published, expected,
                    "{file} must publish the URL the other end of '{}' reaches it at -- the \
                     same one local/keys.sh's `node_url` names in its POST /peers",
                    peering.id
                );
                assert!(
                    config.operator().is_some(),
                    "{file} needs an operator surface: local/keys.sh writes POST /peers to it"
                );
                if *name != "onion" {
                    assert!(
                        config.peer_allow_plaintext_endpoints(),
                        "{file} reads a plaintext self-description in POST /peers (CF-18)"
                    );
                }
                let x402 = match settlement(&config, peering.chain) {
                    SettlementConfig::Evm(evm) => evm.batch_settlement().is_some(),
                    SettlementConfig::Solana(solana) => solana.batch_settlement().is_some(),
                };
                assert!(
                    x402,
                    "{file} must turn on x402 batch-settlement on '{}'s chain",
                    peering.id
                );
            }
        }
    }
}

/// **The `channels` stage opens nothing with a chain CLI** (ADR 0075 decision
/// 13): every channel is opened by its own payer's `POST /peers`, topped up by
/// `POST /channels/:id/fund`, and read back off the chain it lives on. The
/// script that opened TOON's Solana channel is gone.
#[test]
fn local_keys_sh_opens_channels_only_through_the_nodes_own_writes() {
    for write in [
        "operator_request \"$from\" POST /peers",
        "POST \"/channels/$channel/fund\"",
        "POST /routes/peers",
        "docs/operators/sign-write.sh",
    ] {
        assert!(
            code(KEYS_SCRIPT).contains(write),
            "local/keys.sh's `channels` stage must make `{write}`"
        );
    }
    for line in executable_lines(KEYS_SCRIPT) {
        for gone in [
            "openChannel",
            "setTotalDeposit",
            "open-solana-channel",
            "TokenNetwork",
            "getTokenNetwork",
        ] {
            assert!(
                !line.contains(gone),
                "local/keys.sh still does `{gone}`: `{line}`"
            );
        }
    }
    assert!(
        !Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../local/open-solana-channel.py")
            .exists(),
        "local/open-solana-channel.py opened channels of TOON's own Solana program; its last \
         caller was local/keys.sh"
    );
    assert!(
        MAKEFILE.contains("./local/keys.sh $(LOCAL_TOPOLOGY) channels"),
        "`make local-up` must run the `channels` stage once the nodes are serving"
    );
    // The payee writes FIRST, so the payer's very first voucher already
    // arrives on a bound channel, in the peer role.
    let stage = KEYS_SCRIPT
        .split_once("establish_peerings() {")
        .expect("keys.sh defines establish_peerings")
        .1;
    let payee = stage
        .find("establish \"$payee\"")
        .expect("the payee establishes its side");
    let payer = stage
        .find("establish \"$payer\"")
        .expect("the payer establishes its side");
    assert!(payee < payer, "the payee's POST /peers must come first");
}

/// **The rehearsal reads the chain and the payee's voucher journal** --
/// `local/rehearsal.sh`, sourced by every peered topology's sender.
#[test]
fn every_peered_rehearsal_reads_the_chain_and_the_payees_voucher_journal() {
    assert!(
        code(REHEARSAL).contains("client-edge-claims.log")
            && code(REHEARSAL).contains("inbound_claim_accepted"),
        "a voucher is journaled in `client-edge-claims.log` as `inbound_claim_accepted` \
         (`connector_runtime::journal`), whichever role it arrived under"
    );
    assert!(
        code(REHEARSAL).contains(&format!(
            "\\\"to\\\":\\\"{}\\\"",
            ethers::utils::to_checksum(
                &ethers::types::Address::from(connector_signer::X402_BATCH_SETTLEMENT_ADDRESS),
                None
            )
        )),
        "an EVM channel is read off x402BatchSettlement itself"
    );
    assert!(
        code(REHEARSAL).contains(&format!(
            "0x{}",
            hex::encode(&ethers::utils::id("channels(bytes32)")[..4])
        )),
        "with the contract's own `channels(bytes32)` selector"
    );
    assert!(
        code(REHEARSAL).contains(&format!(
            "\"owner\":\"{}\"",
            connector_settlement_solana::batch::wire::PAYMENT_CHANNELS_PROGRAM_ID
        )),
        "a Solana channel must be an account of payment-channels"
    );
    assert!(
        code(REHEARSAL).contains("-j12 -N8"),
        "and its `deposit` is the u64 at offset 12 of the `Channel` layout \
         (`connector_settlement_solana::batch::wire`)"
    );
    assert!(
        code(REHEARSAL).contains("if (accepted != crossings)")
            && code(REHEARSAL).contains("if (step != advance)"),
        "EXACTLY one voucher per crossing, each advancing by exactly the figure owed -- a count \
         or an advance that only has to reach a floor cannot tell a hop keeping its fee from one \
         keeping more"
    );

    for (name, compose) in [
        ("two-hop", TWO_HOP_COMPOSE),
        ("mixed-chain", MIXED_COMPOSE),
        ("dealing", DEALING_COMPOSE),
        ("onion", ONION_COMPOSE),
    ] {
        for needle in [
            ". /app/rehearsal.sh",
            "./local/rehearsal.sh:/app/rehearsal.sh:ro",
            &format!("./local/.keys/{name}/peerings:/app/peerings:ro"),
            "--expect-fulfill",
            "channel_holds ",
            "paid /app/",
        ] {
            assert!(
                code(compose).contains(needle),
                "local/{name}/compose.yml's sender must `{needle}`"
            );
        }
        assert!(
            !compose.contains("peer-claims.log"),
            "local/{name}/compose.yml reads the TOON peer book, which no x402 voucher reaches"
        );
    }
}

/// Every EVM rehearsal checks the collateral keys.sh tops the payer up to.
#[test]
fn every_rehearsal_checks_the_deposit_keys_sh_makes() {
    let deposit = keys_script_constant("CHANNEL_DEPOSIT");
    for (name, compose) in [
        ("two-hop", TWO_HOP_COMPOSE),
        ("mixed-chain", MIXED_COMPOSE),
        ("onion", ONION_COMPOSE),
    ] {
        assert!(
            compose.contains(&format!("DEPOSIT={deposit}")),
            "local/{name}/compose.yml must check the {deposit} local/keys.sh tops up to"
        );
    }
    assert!(DEALING_COMPOSE.contains(&format!("EVM_DEPOSIT={deposit}")));
    let open = keys_script_constant("OPEN_DEPOSIT");
    assert!(
        open < deposit,
        "the channel is OPENED below its target, so `POST /channels/:id/fund` runs on every \
         bring-up"
    );
    let node_usdc = keys_script_constant("NODE_EVM_USDC");
    assert!(
        node_usdc >= deposit + open,
        "a payer cannot deposit USDC it was never minted"
    );
}

// ─── solo ────────────────────────────────────────────────────────────────────

#[test]
fn the_solo_topologys_committed_config_loads() {
    let config = load("local/solo/connector.toml", SOLO_CONFIG);

    assert_eq!(
        config.routes().len(),
        1,
        "solo terminates exactly one route"
    );
    assert_eq!(config.routes()[0].prefix(), "g.local.solo");
    assert_eq!(
        config.settlements().len(),
        2,
        "the point of the solo topology is BOTH settlement backends attached at once"
    );
    assert!(topology("solo").peerings.is_empty());
    assert_eq!(
        config.peer_expose(),
        PeerExposure::Neither,
        "THE DEFAULT, AND IT MUST STAY THE DEFAULT: saying nothing opens no peer listener"
    );
    assert!(config.socks_proxy().is_none());
}

#[test]
fn the_solo_config_and_its_compose_file_agree() {
    for (value, why) in [
        (
            "http://anvil:8545",
            "the EVM rpc_url must name the compose `anvil` service",
        ),
        (
            "http://solana-validator:8899",
            "the Solana rpc_url must name the compose `solana-validator` service",
        ),
        (
            "http://stub-app:3100/",
            "the route's handler_url must name the compose `stub-app` service",
        ),
    ] {
        assert!(SOLO_CONFIG.contains(value), "{why}");
    }
    for service in ["stub-app:", "connector:", "sender:"] {
        assert!(SOLO_COMPOSE.contains(service));
    }
    assert!(SOLO_COMPOSE.contains("./local/solo/connector.toml:/app/config/connector.toml:ro"));
}

// ─── two-hop ─────────────────────────────────────────────────────────────────

/// A forwards, B terminates and PRICES, and the only path between them is the
/// peering -- and ADR 0028's arithmetic across the table and the configs,
/// held here because NOTHING IN THE CODE HOLDS IT.
#[test]
fn the_two_hop_path_adds_up_across_the_table_and_the_configs() {
    let table = topology("two-hop");
    let a = load("local/two-hop/connector-a.toml", TWO_HOP_A);
    let b = load("local/two-hop/connector-b.toml", TWO_HOP_B);

    assert!(
        a.routes().is_empty(),
        "A must terminate NOTHING -- a locally terminated route would give a fulfilled packet a \
         second possible explanation"
    );
    let peering = table.peering("a-b");
    assert_eq!(
        (
            peering.chain,
            peering.payer.as_str(),
            peering.payee.as_str()
        ),
        (SettlementChain::Evm, "connector-a", "connector-b")
    );
    let forward = table.route_on("connector-a");
    assert_eq!(forward.prefix, "g.local.two-hop.b");
    assert_eq!(forward.peer_id, "a-b");
    assert!(
        peering.fee > 0,
        "THE HOP MUST CHARGE (issue #1144): a fee back at zero is a rehearsal that carries for \
         free, and B's journal reads exactly as green either way"
    );

    assert_eq!(b.routes().len(), 1);
    let app = &b.routes()[0];
    assert_eq!(app.prefix(), "g.local.two-hop.b.app");
    assert!(app.prefix().starts_with(&forward.prefix));
    let price = flat(app.price());
    assert!(price > 0, "B both TERMINATES and PRICES this route");
    assert_eq!(
        forward.price - peering.fee,
        price,
        "A collects {}, retains {}, forwards {} -- and B's route costs {price}. Equality, not \
         `>=`: slack is indistinguishable from a discount.",
        forward.price,
        peering.fee,
        forward.price - peering.fee
    );

    for (constant, why) in [
        (
            format!("AMOUNT={}", forward.price),
            "the path's cost, A's price",
        ),
        (
            format!("PRICE={price}"),
            "what each voucher must advance B by",
        ),
        (
            format!("FEE={}", peering.fee),
            "what A must be left holding",
        ),
        (
            "CROSSINGS=2".to_string(),
            "the second crossing is issue #1102's",
        ),
    ] {
        assert!(
            TWO_HOP_COMPOSE.contains(&constant),
            "local/two-hop/compose.yml's sender must set `{constant}`: {why}"
        );
    }
    assert!(TWO_HOP_COMPOSE
        .contains("paid /app/payee-state \"$$CHANNEL\" B \"$$CROSSINGS\" \"$$PRICE\""));
    assert!(TWO_HOP_COMPOSE.contains("--seal-to      http://connector-b:3000/ilp"));
    assert!(TWO_HOP_COMPOSE.contains("two-hop-b-state:/app/payee-state:ro"));

    for (name, config) in [("A", &a), ("B", &b)] {
        assert_eq!(config.settlements().len(), 1, "{name} settles on EVM alone");
        assert_eq!(config.settlements()[0].chain(), SettlementChain::Evm);
    }
}

/// **The peer-role proof** (ADR 0072): B's route is pinned to BTP, B is
/// peered with over ILP-over-HTTP, and a client is held to a pin while a peer
/// is not -- so a crossing that reaches the app arrived on a voucher from the
/// channel B bound to the peering. Without the pin a voucher from an UNBOUND
/// channel would be admitted as a client's and pay the price just as well.
#[test]
fn the_two_hop_payee_can_only_be_paid_in_the_peer_role() {
    let b = load("local/two-hop/connector-b.toml", TWO_HOP_B);
    assert_eq!(b.routes()[0].transport_policy(), TransportPolicy::Btp);
    assert_eq!(b.peer_expose(), PeerExposure::Http);
    assert!(
        b.node().and_then(|node| node.btp_endpoint()).is_none(),
        "B publishes no BTP endpoint, so A's POST /peers dials ILP-over-HTTP -- the carriage the \
         route's pin refuses a client on"
    );
}

// ─── mixed-chain ─────────────────────────────────────────────────────────────

/// One node holding two settlement backends with a peering on each, so a
/// packet crosses a chain boundary between two hops -- and NOT a conversion:
/// no config here declares `[[tokens]]` (ADR 0071's absence rule).
#[test]
fn the_mixed_chain_topology_puts_one_node_on_both_chains() {
    let a = load("local/mixed-chain/connector-a.toml", MIXED_A);
    let b = load("local/mixed-chain/connector-b.toml", MIXED_B);
    let c = load("local/mixed-chain/connector-c.toml", MIXED_C);
    let table = topology("mixed-chain");

    assert_eq!(a.settlements().len(), 1);
    assert_eq!(a.settlements()[0].chain(), SettlementChain::Evm);
    assert_eq!(c.settlements().len(), 1);
    assert_eq!(c.settlements()[0].chain(), SettlementChain::Solana);
    let mut chains: Vec<SettlementChain> = b.settlements().iter().map(|s| s.chain()).collect();
    chains.sort_by_key(|chain| format!("{chain:?}"));
    assert_eq!(chains, vec![SettlementChain::Evm, SettlementChain::Solana]);
    assert_eq!(table.peering("a-b").chain, SettlementChain::Evm);
    assert_eq!(table.peering("b-c").chain, SettlementChain::Solana);
    for (name, config) in [("A", &a), ("B", &b), ("C", &c)] {
        assert!(
            !config.denomination().declares_tokens(),
            "{name} declares tokens: this topology is the UNCONVERTED chain boundary"
        );
    }
}

#[test]
fn the_mixed_chain_path_is_one_prefix_per_hop_and_one_flat_fee_per_hop() {
    let table = topology("mixed-chain");
    let a = load("local/mixed-chain/connector-a.toml", MIXED_A);
    let b = load("local/mixed-chain/connector-b.toml", MIXED_B);
    let c = load("local/mixed-chain/connector-c.toml", MIXED_C);

    assert!(a.routes().is_empty(), "A is a hop");
    assert_eq!(
        b.routes().len(),
        1,
        "B is a hop, with exactly one terminated route: the a-b leg's peer-role proof"
    );
    assert_eq!(c.routes().len(), 1);
    let first = table.route_on("connector-a");
    let second = table.route_on("connector-b");
    let app = &c.routes()[0];
    assert_eq!(
        (first.prefix.as_str(), first.peer_id.as_str()),
        ("g.local.mixed.b", "a-b")
    );
    assert_eq!(
        (second.prefix.as_str(), second.peer_id.as_str()),
        ("g.local.mixed.b.c", "b-c")
    );
    assert_eq!(app.prefix(), "g.local.mixed.b.c.app");
    assert!(second.prefix.starts_with(&first.prefix) && app.prefix().starts_with(&second.prefix));

    let first_fee = table.peering("a-b").fee;
    let second_fee = table.peering("b-c").fee;
    assert!(
        first_fee > 0 && second_fee > 0,
        "every forwarding hop charges (#1144)"
    );
    assert_ne!(
        first_fee, second_fee,
        "equal fees would let a hop charging the wrong one pass unnoticed"
    );
    assert_eq!(
        first.price - first_fee,
        second.price,
        "STILL NOT A CONVERSION: what leaves A is what arrived minus A's flat fee, exactly B's \
         price"
    );
    assert_eq!(
        flat(app.price()),
        0,
        "C's termination is unpriced by choice"
    );

    let owed_at_b = first.price - first_fee;
    let owed_at_c = second.price - second_fee;
    for constant in [
        format!("AMOUNT={}", first.price),
        format!("OWED_AT_B={owed_at_b}"),
        format!("OWED_AT_C={owed_at_c}"),
        "CROSSINGS=2".to_string(),
    ] {
        assert!(
            MIXED_COMPOSE.contains(&constant),
            "local/mixed-chain/compose.yml's sender must set `{constant}`"
        );
    }
    assert!(MIXED_COMPOSE.contains(
        "paid /app/b-state \"$$A_B\" \"B (EVM)\" \"$$((CROSSINGS + 1))\" \"$$OWED_AT_B\""
    ));
    assert!(MIXED_COMPOSE.contains("paid /app/c-state \"$$B_C\""));
    assert!(MIXED_COMPOSE.contains("--seal-to      http://connector-c:3000/ilp"));
}

/// **The middle hop's peer-role proof** (`mixed-chain` and `dealing`): B
/// forwards everything else, and a runtime forwarding route cannot be pinned,
/// so B terminates one route pinned to the carriage A does NOT pay B over,
/// priced at exactly what A forwards. A client is refused it and a peer is
/// not; the rehearsal sends one packet there on the same channel as its
/// forwards, so reaching it proves that channel is bound to the peering. B's
/// journal is then held to one more voucher than the forwards alone.
#[test]
fn the_middle_hop_can_only_be_paid_in_the_peer_role() {
    for (name, raw, compose, pin, prefix) in [
        (
            "mixed-chain",
            MIXED_B,
            MIXED_COMPOSE,
            TransportPolicy::Http,
            "g.local.mixed.b.app",
        ),
        (
            "dealing",
            DEALING_B,
            DEALING_COMPOSE,
            TransportPolicy::Btp,
            "g.local.dealing.b.app",
        ),
    ] {
        let table = topology(name);
        let b = load(&format!("local/{name}/connector-b.toml"), raw);
        let proof = &b.routes()[0];
        assert_eq!(proof.prefix(), prefix);
        assert_eq!(
            proof.transport_policy(),
            pin,
            "{name}'s B pins its proof route to the carriage A does not pay it over"
        );
        let a_pays_over_btp = b.node().and_then(|node| node.btp_endpoint()).is_some();
        assert_eq!(
            a_pays_over_btp,
            pin == TransportPolicy::Http,
            "{name}: the pin must be the OTHER carriage, or a client over the peering's own \
             carriage would reach it too"
        );
        let forward = table.route_on("connector-a");
        assert_eq!(
            flat(proof.price()),
            forward.price - table.peering("a-b").fee,
            "{name}: priced at exactly what A forwards, so the journal holds it to the same \
             figure as every forward"
        );
        assert!(
            code(compose).contains(&format!("--to           {prefix}")),
            "{name}'s sender must send the proof crossing"
        );
    }
}

/// **The carriage each peering rides, pinned** (issue #1155): `a-b` over BTP
/// -- B publishes a BTP endpoint, which `POST /peers` prefers, and exposes no
/// ILP-over-HTTP peer carriage -- and `b-c` over ILP-over-HTTP, so one packet
/// crosses both carriages as well as both chains. `two-hop` stays on HTTP.
#[test]
fn the_local_topologies_run_both_carriages_and_not_by_accident() {
    let a = load("local/mixed-chain/connector-a.toml", MIXED_A);
    let b = load("local/mixed-chain/connector-b.toml", MIXED_B);
    let c = load("local/mixed-chain/connector-c.toml", MIXED_C);

    assert_eq!(
        b.node().and_then(|node| node.btp_endpoint()),
        Some("ws://connector-b:3000/ilp/btp"),
        "B publishes the BTP endpoint A's POST /peers dials"
    );
    assert_eq!(b.peer_expose(), PeerExposure::Btp);
    assert!(a.node().and_then(|node| node.btp_endpoint()).is_none());
    assert!(
        c.node().and_then(|node| node.btp_endpoint()).is_none(),
        "C publishes HTTP only, so B pays C over ILP-over-HTTP"
    );
    assert_eq!(c.peer_expose(), PeerExposure::Http);
    assert_eq!(
        c.routes()[0].transport_policy(),
        TransportPolicy::Btp,
        "the PEER-ROLE PROOF on the Solana leg: a client arriving over HTTP is refused a route \
         pinned to BTP, a peer is not"
    );
}

// ─── dealing ─────────────────────────────────────────────────────────────────

/// What one crossing must advance each payee's channel by, in that payee's own
/// unit.
const DEALING_OWED_AT_B: u64 = 1100;
const DEALING_OWED_AT_C: u64 = 4_350_000;

fn settlement_decimals(settlement: &SettlementConfig) -> u8 {
    match settlement {
        SettlementConfig::Evm(evm) => evm.decimals(),
        SettlementConfig::Solana(solana) => solana.decimals(),
    }
}

/// The two tokens B's peerings deal in: the token of the chain each settles
/// on (#1382 -- a runtime x402 peering's token is read off its own channel
/// binding, whose chain names it).
fn dealing_boundary(b: &Config) -> (AssetId, AssetId) {
    let table = topology("dealing");
    (
        settlement(b, table.peering("a-b").chain).asset(),
        settlement(b, table.peering("b-c").chain).asset(),
    )
}

/// What one crossing forwards across the boundary, computed the way the
/// forwarding path computes it: the rate table `build()` makes, the pair
/// looked up the way `Connector::crossing` does, and the table's fee run
/// through `amount_after_rate_and_fee`.
fn dealing_forwarded_amount(b: &Config) -> u64 {
    let table = topology("dealing");
    let onward = table.route_on("connector-b");
    let rates = SharedRateTable::from_config(b.denomination())
        .expect("a node with a declared rate has a table");
    let (incoming, outgoing) = dealing_boundary(b);
    let rate = rates
        .lookup(&incoming, &outgoing, chrono::Utc::now())
        .rate()
        .expect("a STATIC row never goes stale");
    amount_after_rate_and_fee(onward.price, rate, table.peering("b-c").fee)
        .expect("the converted amount must survive this hop's fee")
}

/// **Only the middle node deals, and that is the assertion** (ADR 0071).
#[test]
fn the_dealing_topologys_committed_configs_load() {
    let a = load("local/dealing/connector-a.toml", DEALING_A);
    let b = load("local/dealing/connector-b.toml", DEALING_B);
    let c = load("local/dealing/connector-c.toml", DEALING_C);

    for (name, config) in [("A", &a), ("C", &c)] {
        assert!(
            !config.denomination().declares_tokens(),
            "{name} declares tokens: the two ends of this path are ORDINARY nodes"
        );
    }
    assert!(
        b.denomination().declares_tokens(),
        "B is the only node here that deals"
    );
    let (incoming, outgoing) = dealing_boundary(&b);
    assert_eq!(
        b.denomination().numeraire(),
        Some(&incoming),
        "the numeraire is the 6-decimal USDC the incoming leg holds"
    );
    assert_eq!(
        b.denomination().rates().len(),
        1,
        "one ordered pair, declared once"
    );
    assert!(b.denomination().guards().is_some());
    assert_eq!(b.denomination().quoted_tokens().count(), 0);
    assert_ne!(incoming, outgoing);
}

/// **The two legs hold different tokens, different in SCALE**, which is what
/// makes this a boundary an unconverted pass-through would be wrong at.
#[test]
fn the_dealing_hop_sits_on_a_real_denomination_boundary() {
    let b = load("local/dealing/connector-b.toml", DEALING_B);
    let (incoming, outgoing) = dealing_boundary(&b);
    assert_eq!(incoming.chain(), connector_domain::AssetChain::Evm);
    assert_eq!(outgoing.chain(), connector_domain::AssetChain::Solana);
    assert_ne!(
        settlement_decimals(settlement(&b, SettlementChain::Evm)),
        settlement_decimals(settlement(&b, SettlementChain::Solana)),
        "the two legs must differ in DECIMALS as well as in identity -- a crossing at par \
         cannot tell a correct conversion from none"
    );
    assert!(
        SharedRateTable::from_config(b.denomination())
            .expect("a table")
            .lookup(&incoming, &outgoing, chrono::Utc::now())
            .rate()
            .is_some(),
        "B declares the rate for exactly this ordered pair"
    );
}

/// **The covering voucher is signed for the CONVERTED figure, and the
/// rehearsal asserts that figure** (ADR 0071 decision 1).
#[test]
fn the_dealing_crossing_is_covered_for_the_converted_figure() {
    let table = topology("dealing");
    let b = load("local/dealing/connector-b.toml", DEALING_B);
    let c = load("local/dealing/connector-c.toml", DEALING_C);

    let first = table.route_on("connector-a");
    let second = table.route_on("connector-b");
    assert_eq!(first.prefix, "g.local.dealing.b");
    assert_eq!(second.prefix, "g.local.dealing.b.c");
    assert_eq!(
        first.price - table.peering("a-b").fee,
        second.price,
        "what A forwards is its price less its flat fee, exactly B's price"
    );
    assert_eq!(second.price, DEALING_OWED_AT_B);

    let forwarded = dealing_forwarded_amount(&b);
    assert_eq!(
        forwarded, DEALING_OWED_AT_C,
        "`floor(1100 * 4000/1 * 99/100) - 6000`"
    );
    assert!(
        forwarded > second.price * 1000,
        "more than a thousand times the arriving figure, or the scale half of the rate is gone"
    );

    for constant in [
        format!("AMOUNT={}", first.price),
        format!("OWED_AT_B={DEALING_OWED_AT_B}"),
        format!("OWED_AT_C={DEALING_OWED_AT_C}"),
        "CROSSINGS=2".to_string(),
    ] {
        assert!(
            DEALING_COMPOSE.contains(&constant),
            "local/dealing/compose.yml's sender must set `{constant}` -- the CONVERTED figure is \
             the one assertion `--expect-fulfill` cannot make for itself"
        );
    }
    assert!(DEALING_COMPOSE.contains(
        "paid /app/c-state \"$$B_C\" \"C (Solana, 9dp mock)\" \"$$CROSSINGS\" \"$$OWED_AT_C\""
    ));
    assert!(DEALING_COMPOSE.contains(
        "paid /app/b-state \"$$A_B\" \"B (EVM, 6dp USDC)\" \"$$((CROSSINGS + 1))\" \"$$OWED_AT_B\""
    ));
    assert_eq!(flat(c.routes()[0].price()), 0);
    assert_eq!(
        c.routes()[0].transport_policy(),
        TransportPolicy::Btp,
        "the peer-role proof on the converted leg"
    );
}

/// **The outgoing peering writes its own cap, in the outgoing leg's unit, and
/// it has to**: the default is one USDC at six decimals and is checked against
/// the amount actually going out, post-conversion.
#[test]
fn the_dealing_outgoing_cap_is_written_in_the_outgoing_leg_unit() {
    let table = topology("dealing");
    let b = load("local/dealing/connector-b.toml", DEALING_B);
    let forwarded = dealing_forwarded_amount(&b);
    let cap = table.peering("b-c").max_packet_amount;
    assert!(
        cap >= forwarded,
        "the cap must admit the converted amount ({cap} vs {forwarded})"
    );
    assert!(
        forwarded > connector_config::DEFAULT_MAX_PACKET_AMOUNT,
        "and the DEFAULT must not admit it, or the written cap is decoration"
    );
    assert_eq!(
        table.peering("a-b").max_packet_amount,
        0,
        "the arriving peering keeps the default, denominated in the 6-decimal unit it was \
         chosen in"
    );
}

/// The Solana leg is funded in its OWN unit: a hundred tokens at nine decimals
/// is a thousand times the base units of a hundred at six.
#[test]
fn the_dealing_solana_channel_is_funded_in_the_outgoing_leg_unit() {
    let deposit = keys_script_constant("DEALING_CHANNEL_DEPOSIT");
    let usdc_deposit = keys_script_constant("CHANNEL_DEPOSIT");
    assert!(deposit > usdc_deposit);
    assert!(deposit >= u128::from(DEALING_OWED_AT_C));
    assert!(
        code(KEYS_SCRIPT).contains("SOLANA_CHANNEL_DEPOSIT=\"$DEALING_CHANNEL_DEPOSIT\""),
        "local/keys.sh must top the dealing Solana leg up to its own figure"
    );
    assert!(DEALING_COMPOSE.contains(&format!("SOLANA_DEPOSIT={deposit}")));
    let node_tokens = keys_script_constant("NODE_SOLANA_TOKENS");
    let decimals = keys_script_constant("DEALING_MINT_DECIMALS");
    assert!(
        node_tokens * 10u128.pow(decimals as u32) >= deposit + keys_script_constant("OPEN_DEPOSIT"),
        "local/keys.sh gives each node too little of the mint to fund its channel"
    );
}

/// The topology's own mint: created by `local/keys.sh`, its keypair derived
/// rather than committed, and its address asserted against every config.
#[test]
fn the_dealing_topology_owns_its_mint_and_commits_no_key_for_it() {
    let b = load("local/dealing/connector-b.toml", DEALING_B);
    let c = load("local/dealing/connector-c.toml", DEALING_C);
    let mint = settlement(&b, SettlementChain::Solana).asset();
    assert!(!mint
        .to_string()
        .contains("H8HSreUF2s8r8hem4qMttE3bWYCpFuh71jbuos5bA77H"));
    assert_eq!(
        mint,
        c.settlements()[0].asset(),
        "both ends of b-c hold the same mint"
    );
    assert!(code(KEYS_SCRIPT).contains("DEALING_MINT_INDEX="));
    assert!(code(KEYS_SCRIPT).contains("spl-token create-token --config \"$SOLANA_SPL_CONFIG\""));
    assert!(code(KEYS_SCRIPT).contains("config_must_name \"$SOLANA_MINT\""));
}

#[test]
fn the_dealing_configs_and_their_compose_file_agree() {
    for node in ["connector-a", "connector-b", "connector-c"] {
        assert!(DEALING_COMPOSE.contains(&format!(
            "./local/dealing/{node}.toml:/app/config/connector.toml:ro"
        )));
    }
    for (volume, mount) in [
        ("dealing-b-state", "b-state"),
        ("dealing-c-state", "c-state"),
    ] {
        assert!(DEALING_COMPOSE.contains(&format!("{volume}:/app/{mount}:ro")));
    }
    assert!(DEALING_COMPOSE.contains("--seal-to      http://connector-c:3000/ilp"));
}

/// **This topology IS on the CI gate** -- the mirror of
/// [`the_onion_topology_is_deliberately_not_on_the_ci_gate`].
#[test]
fn the_dealing_topology_is_on_the_ci_gate() {
    assert!(LOCAL_TOPOLOGIES_WORKFLOW.contains("topology: [solo, two-hop, mixed-chain, dealing]"));
    assert!(LOCAL_README.contains("### Why it IS on the CI gate"));
}

// ─── onion ───────────────────────────────────────────────────────────────────

/// The one service block `local/onion/compose.yml` declares under `service`.
fn onion_service(service: &str) -> &'static str {
    let head = format!("\n  {service}:\n");
    let start = ONION_COMPOSE
        .find(&head)
        .unwrap_or_else(|| panic!("local/onion/compose.yml declares no `{service}` service"))
        + head.len();
    let body = &ONION_COMPOSE[start..];
    let mut end = body.len();
    let mut offset = 0;
    for line in body.lines() {
        if !line.is_empty() && !line.starts_with("    ") {
            end = offset;
            break;
        }
        offset += line.len() + 1;
    }
    &body[..end]
}

#[test]
fn the_onion_topologys_committed_configs_load() {
    let table = topology("onion");
    let a = load("local/onion/connector-a.toml", ONION_A);
    let b = load("local/onion/connector-b.toml", ONION_B);

    assert!(a.routes().is_empty(), "A must terminate NOTHING");
    let forward = table.route_on("connector-a");
    let peering = table.peering("a-b");
    assert_eq!(forward.prefix, "g.local.onion.b");
    assert_eq!(b.routes().len(), 1);
    assert_eq!(b.routes()[0].prefix(), "g.local.onion.b.app");
    assert!(
        peering.fee > 0,
        "a peering carried over a circuit is priced like any other"
    );
    assert_eq!(forward.price - peering.fee, flat(b.routes()[0].price()));
    assert_ne!(
        (forward.price, peering.fee),
        (1100, 100),
        "these are `two-hop`'s figures; two topologies sharing one set is how a copied config \
         passes unnoticed"
    );
    for (name, config) in [("A", &a), ("B", &b)] {
        assert_eq!(config.settlements().len(), 1, "{name} settles on EVM alone");
        assert_eq!(config.settlements()[0].chain(), SettlementChain::Evm);
    }
}

/// **The host is the only thing that changed** (ADR 0070): an onion endpoint
/// adds no third carriage, and each node dials the other's hidden-service
/// URLs through the one proxy on its own network.
#[test]
fn the_onion_peering_is_an_ordinary_btp_peering_at_an_extraordinary_host() {
    let a = load("local/onion/connector-a.toml", ONION_A);
    let b = load("local/onion/connector-b.toml", ONION_B);

    let btp = b
        .node()
        .and_then(|node| node.btp_endpoint())
        .expect("B publishes the BTP endpoint A's POST /peers prefers");
    let btp = url::Url::parse(btp).expect("a URL");
    assert!(connector_config::is_onion_endpoint(&btp));
    assert_eq!(
        connector_config::PeerCarriage::for_endpoint(&btp, false),
        Some(connector_config::PeerCarriage::Btp),
        "`ws://` selects BTP at an onion host with no plaintext opt-in -- the host takes no \
         part in choosing the carriage"
    );
    assert_eq!(b.peer_expose(), PeerExposure::Btp);
    assert_eq!(
        b.routes()[0].transport_policy(),
        TransportPolicy::Http,
        "the PEER-ROLE PROOF: A peers over BTP, a client over BTP is refused a route pinned to \
         HTTP, a peer is not"
    );

    for (name, config, sidecar) in [("A", &a, "anon-a"), ("B", &b, "anon-b")] {
        let proxy = config
            .socks_proxy()
            .unwrap_or_else(|| panic!("{name} dials the other's onion URLs, so it names a proxy"));
        assert_eq!(
            proxy.scheme(),
            "socks5h",
            "resolution has to happen AT the proxy"
        );
        assert_eq!(proxy.host_str(), Some(sidecar), "{name}'s own sidecar");
        assert!(
            !config.peer_allow_plaintext_endpoints(),
            "{name} must load without the plaintext opt-in -- ADR 0070's exemption is keyed on \
             the host"
        );
    }
    for (name, raw) in [
        ("local/onion/connector-a.toml", ONION_A),
        ("local/onion/connector-b.toml", ONION_B),
    ] {
        assert!(
            !raw.contains("peer_allow_plaintext_endpoints = true"),
            "{name}"
        );
    }
    for (name, config) in [
        ("local/solo/connector.toml", SOLO_CONFIG),
        ("local/two-hop/connector-a.toml", TWO_HOP_A),
        ("local/mixed-chain/connector-a.toml", MIXED_A),
    ] {
        assert!(
            load(name, config).socks_proxy().is_none(),
            "{name} dials no onion endpoint and configures no proxy"
        );
    }
}

/// **The addresses the operator writes down** (ADR 0070 decision 7): the
/// committed configs carry placeholders, `local/keys.sh` renders each
/// daemon's address in, and compose mounts the rendered files.
#[test]
fn the_onion_topology_commits_placeholders_and_mounts_what_keys_sh_renders() {
    assert!(ONION_A.contains(ONION_PLACEHOLDER_A) && !ONION_A.contains(ONION_PLACEHOLDER_B));
    assert!(ONION_B.contains(ONION_PLACEHOLDER_B) && !ONION_B.contains(ONION_PLACEHOLDER_A));
    for placeholder in [
        format!("ONION_PLACEHOLDER_A={ONION_PLACEHOLDER_A}"),
        format!("ONION_PLACEHOLDER_B={ONION_PLACEHOLDER_B}"),
    ] {
        assert!(
            code(KEYS_SCRIPT).contains(&placeholder),
            "local/keys.sh must substitute the same literal the committed configs carry"
        );
    }
    assert!(code(KEYS_SCRIPT).contains("cat /var/lib/anon/hidden_service/hostname"));
    assert!(
        code(KEYS_SCRIPT).contains("onion_address anon-a")
            && code(KEYS_SCRIPT).contains("onion_address anon-b")
    );
    for node in ["connector-a", "connector-b"] {
        assert!(ONION_COMPOSE.contains(&format!(
            "./local/.keys/onion/{node}/connector.toml:/app/config/connector.toml:ro"
        )));
        assert!(!ONION_COMPOSE.contains(&format!("./local/onion/{node}.toml:")));
    }
}

#[test]
fn the_onion_sidecar_is_the_daemon_that_writes_the_placeholders_tld() {
    assert!(ONION_PLACEHOLDER_A.ends_with(ANON_TLD) && ONION_PLACEHOLDER_B.ends_with(ANON_TLD));
    assert!(ANON_IMAGE_DOCKERFILE.contains(&format!("ARG ANON_VERSION={ANON_VERSION}")));
    assert!(ANON_IMAGE_DOCKERFILE.contains("sha256sum -c -"));
    assert!(ANON_IMAGE_DOCKERFILE.contains("anon --version | grep -q \"0.4.10.2\""));
    for service in ["anon-a", "anon-b"] {
        let block = onion_service(service);
        assert!(block.contains("context: ./local/anon-image"));
        assert!(block.contains(&format!("image: anon-live:{ANON_VERSION}")));
    }
    assert!(!ONION_COMPOSE.contains("ator-protocol:v0.4.9.7"));
    assert!(code(KEYS_SCRIPT).contains(&format!("{{56}}\\{ANON_TLD}$")));
}

/// **No route between the connectors** (ADR 0070's Consequences): each on its
/// own network, `anvil` on both, neither network `internal`, B no host port.
#[test]
fn each_onion_connector_is_on_its_own_network_with_no_route_to_the_other() {
    for (service, network) in [
        ("anon-a", "onion-a"),
        ("sender", "onion-a"),
        ("anon-b", "onion-b"),
        ("stub-app", "onion-b"),
    ] {
        assert!(
            onion_service(service).contains(&format!("networks: [{network}]")),
            "`{service}` must be on `{network}` and on nothing else"
        );
    }
    for (service, own, other) in [
        ("connector-a", "onion-a", "onion-b"),
        ("connector-b", "onion-b", "onion-a"),
    ] {
        let block = onion_service(service);
        assert!(
            block.contains(&format!("\n      {own}:\n")),
            "`{service}` on `{own}`"
        );
        assert!(!block.contains(other), "`{service}` never on `{other}`");
    }
    assert!(onion_service("anvil").contains("networks: [onion-a, onion-b]"));
    assert!(!ONION_COMPOSE.contains("internal: true"));
    assert!(!onion_service("connector-b").contains("ports:"));
    assert!(onion_service("connector-a").contains("'127.0.0.1:3006:3000'"));
    assert!(onion_service("sender").contains("onion-b-state:/app/payee-state:ro"));
    assert!(
        onion_service("sender").contains("./local/.keys/onion/connector-b/onion-hostname:"),
        "the sender reads B's address out of what keys.sh recorded -- one file, nothing of B's \
         keys"
    );
}

/// What ADR 0070 says each `anon` sidecar's configuration has to carry: the
/// terms flag, and a hidden service persisted on a named volume -- now on
/// BOTH sides, because each node's self-description is read over a circuit
/// by the other's `POST /peers`. Each targets its connector by a fixed IP,
/// because `anon` resolves that target when it PARSES its config.
#[test]
fn the_onion_sidecars_agree_to_the_terms_and_persist_the_hidden_service() {
    for (name, anonrc, service, volume, addr, connector) in [
        (
            "anonrc-a",
            ONION_ANONRC_A,
            "anon-a",
            "onion-a-anon",
            ONION_A_ADDR,
            "connector-a",
        ),
        (
            "anonrc-b",
            ONION_ANONRC_B,
            "anon-b",
            "onion-b-anon",
            ONION_B_ADDR,
            "connector-b",
        ),
    ] {
        assert!(
            anonrc.lines().any(|line| line.trim() == "AgreeToTerms 1"),
            "{name}"
        );
        assert!(
            anonrc.lines().any(|line| line.starts_with("Nickname ")),
            "{name}"
        );
        assert!(
            anonrc.contains("HiddenServiceDir /var/lib/anon/hidden_service"),
            "{name}"
        );
        assert!(
            onion_service(service).contains(&format!("{volume}:/var/lib/anon")),
            "{name}"
        );
        assert!(ONION_COMPOSE.contains(&format!("\n  {volume}:")), "{name}");
        assert!(
            anonrc.contains(&format!("HiddenServicePort 80 {addr}:3000")),
            "{name}: ONE onion port for every surface of its connector"
        );
        assert!(
            !anonrc.contains(&format!("{connector}:3000")),
            "{name}: an IP, never a name"
        );
        assert!(
            onion_service(connector).contains(&format!("ipv4_address: {addr}")),
            "{name}"
        );
        assert!(
            anonrc.contains("SocksPort 0.0.0.0:9050"),
            "{name}: its connector's `socks_proxy`"
        );
    }
    assert!(ONION_COMPOSE.contains("subnet: 172.29.0.0/24"));
    assert!(ONION_COMPOSE.contains("subnet: 172.31.0.0/24"));
}

#[test]
fn the_onion_rehearsal_reads_the_payees_own_voucher_journal() {
    let table = topology("onion");
    let b = load("local/onion/connector-b.toml", ONION_B);
    let sender = onion_service("sender");
    let price = flat(b.routes()[0].price());
    let fee = table.peering("a-b").fee;
    for constant in [
        format!("PRICE={price}"),
        format!("FEE={fee}"),
        format!("AMOUNT={}", price + fee),
        "CROSSINGS=2".to_string(),
    ] {
        assert!(
            sender.contains(&constant),
            "the onion sender must set `{constant}`"
        );
    }
    assert!(sender.contains("paid /app/payee-state \"$$CHANNEL\" B \"$$CROSSINGS\" \"$$PRICE\""));
    assert!(sender.contains("--expect-fulfill"));
    assert!(sender.contains("--socks-proxy"));
    assert!(sender.contains("--dry-run"));
    assert!(!sender.contains(ONION_PLACEHOLDER_B));
}

/// **This topology is deliberately not on the CI gate, and this is the test
/// that keeps it off**: a gate that goes red when a third-party anonymity
/// network has a bad day is the run-or-fail-loudly rule inverted.
#[test]
fn the_onion_topology_is_deliberately_not_on_the_ci_gate() {
    assert!(LOCAL_TOPOLOGIES_WORKFLOW.contains("topology: [solo, two-hop, mixed-chain, dealing]"));
    assert!(!LOCAL_TOPOLOGIES_WORKFLOW.contains("onion"));
    assert!(LOCAL_README.contains("## Why the onion topology is not on the CI gate"));
    assert!(LOCAL_README.contains("either runs or fails loudly"));
}

// ─── one stack per machine ───────────────────────────────────────────────────

/// Every target here works in ONE compose project, named in the compose file
/// rather than inherited from the directory (issue #1122).
#[test]
fn every_local_target_names_one_compose_project() {
    assert!(ROOT_COMPOSE.contains("\nname: connector\n"));
    assert!(MAKEFILE.contains("LOCAL_PROJECT := connector"));
    assert!(MAKEFILE.contains("$(LOCAL_COMPOSE) down -v --remove-orphans"));
    assert!(MAKEFILE.contains(
        "docker volume ls -q --filter label=com.docker.compose.project=$(LOCAL_PROJECT)"
    ));
    for guarded in ["local-up: local-preflight", "local-verify: local-preflight"] {
        assert!(MAKEFILE.contains(guarded), "`{guarded}` must hold");
    }
}

// ─── packages/contracts' pins ────────────────────────────────────────────────

/// `packages/contracts/foundry.lock`'s revisions are the committed
/// submodules'. No local chain compiles those contracts any more (the anvil
/// service places committed bytecode), but the host-side `forge build`
/// `abi_provenance` runs still does, against the libs
/// `tools/contracts/init-libs.sh` pins, until #1386 removes the package -- so
/// the lockfile must still name what the tree commits (issue #1121).
#[test]
fn the_lockfile_names_the_committed_submodule_revisions() {
    let Some(root) = git_checkout_root() else {
        return;
    };

    for lib in ["lib/forge-std", "lib/openzeppelin-contracts"] {
        let path = format!("packages/contracts/{lib}");
        let listed = Command::new("git")
            .args(["ls-tree", "HEAD", "--", &path])
            .current_dir(&root)
            .output()
            .expect("run git ls-tree");
        let listed = String::from_utf8(listed.stdout).expect("git ls-tree output is utf-8");
        let committed = listed
            .split_whitespace()
            .nth(2)
            .unwrap_or_else(|| panic!("git ls-tree names no submodule at {path}: {listed:?}"))
            .to_owned();
        assert_eq!(committed, locked_revision(lib), "{lib}");
    }
}

fn locked_revision(lib: &str) -> String {
    let lock: serde_json::Value =
        serde_json::from_str(FOUNDRY_LOCK).expect("packages/contracts/foundry.lock is JSON");
    lock[lib]["tag"]["rev"]
        .as_str()
        .unwrap_or_else(|| panic!("packages/contracts/foundry.lock records no revision for {lib}"))
        .to_owned()
}

/// The repository root, when this is a git checkout with git on PATH. Panics
/// under `CI` rather than skipping: the gate runs against a clone.
fn git_checkout_root() -> Option<PathBuf> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let toplevel = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .current_dir(&root)
        .output();
    match toplevel {
        Ok(output) if output.status.success() => Some(root),
        _ => {
            assert!(
                std::env::var_os("CI").is_none(),
                "this is not a git checkout (or git is not on PATH), but CI is set"
            );
            eprintln!("skipping: not a git checkout -- this test only skips outside CI");
            None
        }
    }
}
