//! ADR 0074 decision 7: the committed EVM voucher vector, checked against
//! the deployed contract's own `getChannelId` and `getVoucherDigest`, so the
//! vector cannot drift from the chain it names.
//!
//! `vectors/wire-vectors.json`'s `claim_voucher.evm` case is generated by
//! `connector-vectors` from this workspace's own EIP-712 code. That code
//! agreeing with itself proves nothing about x402; this test hands the
//! vector's `ChannelConfig` and amount to Base Sepolia's
//! `x402BatchSettlement` runtime bytecode, placed at its canonical address
//! on an `anvil` running as chain **84532** -- the vector's own chain id,
//! and the one its EIP-712 domain separator commits to -- and asserts the
//! contract answers the committed `channelId` and digest.

use connector_settlement::batch::EvmChannelConfig;
use connector_settlement_evm::test_support::x402::X402Chain;
use connector_settlement_evm::test_support::{require_anvil, Anvil};
use serde_json::Value;

/// This binary's own base port for [`Anvil::spawn_with_chain_id`], clear of
/// every other anvil binary's range.
const ANVIL_BASE_PORT: u16 = 22_900;

const WIRE_VECTORS: &str = include_str!("../../../vectors/wire-vectors.json");

fn bytes<const N: usize>(case: &Value, field: &str) -> [u8; N] {
    let text = case[field]
        .as_str()
        .unwrap_or_else(|| panic!("the vector's '{field}' is a hex string"));
    assert_eq!(text.len(), 2 * N, "'{field}' is {N} bytes of hex");
    let mut out = [0u8; N];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&text[2 * i..2 * i + 2], 16)
            .unwrap_or_else(|_| panic!("'{field}' is hex"));
    }
    out
}

#[tokio::test]
async fn the_evm_voucher_vector_is_what_the_deployed_contract_computes() {
    if !require_anvil() {
        return;
    }
    let vectors: Value = serde_json::from_str(WIRE_VECTORS).expect("the committed vectors parse");
    let case = &vectors["claim_voucher"]["evm"];
    let chain_id = case["chain_id"]
        .as_u64()
        .expect("the vector names its chain");
    assert_eq!(
        chain_id, 84_532,
        "the vector is Base Sepolia's; if it moved, so must this test's chain"
    );
    let verifying_contract: [u8; 20] = bytes(case, "verifying_contract_hex");
    assert_eq!(
        verifying_contract,
        connector_signer::X402_BATCH_SETTLEMENT_ADDRESS,
        "the vector's verifying contract is the one this connector binds to"
    );

    let anvil = Anvil::spawn_with_chain_id(ANVIL_BASE_PORT, chain_id).await;
    let x402 = X402Chain::place(&anvil.rpc_url).await;
    assert_eq!(x402.chain_id(), chain_id);

    let config = &case["channel_config"];
    let config = EvmChannelConfig {
        payer: bytes(config, "payer_hex"),
        payer_authorizer: bytes(config, "payer_authorizer_hex"),
        receiver: bytes(config, "receiver_hex"),
        receiver_authorizer: bytes(config, "receiver_authorizer_hex"),
        token: bytes(config, "token_hex"),
        withdraw_delay: config["withdraw_delay"].as_u64().expect("a delay"),
        salt: bytes(config, "salt_hex"),
    };
    let channel_id: [u8; 32] = bytes(case, "channel_id_hex");
    assert_eq!(
        x402.contract_channel_id(&config).await,
        channel_id,
        "x402BatchSettlement.getChannelId(config) is the vector's channelId"
    );

    let amount = u128::from(
        case["max_claimable_amount"]
            .as_u64()
            .expect("the vector's amount"),
    );
    let digest: [u8; 32] = bytes(case, "digest_hex");
    assert_eq!(
        x402.contract_voucher_digest(channel_id, amount).await,
        digest,
        "x402BatchSettlement.getVoucherDigest(channelId, amount) is the vector's digest"
    );
}
