//! ADR 0074 decision 7: the committed EVM voucher vectors, checked against
//! the deployed contract's own `getChannelId` and `getVoucherDigest`, so no
//! vector can drift from the chain it names. Since `schema_version` 7 (ADR
//! 0075, issue #1384) that is every EVM voucher the set pins:
//! `claim_voucher.evm`, `peer_carriage.voucher_evm` and `payout_voucher.evm`,
//! which carry the same fields under the same names -- plus, since
//! `schema_version` 8 (issue #1429), `claim_voucher.evm_above_u64_max`, whose
//! amount only a `uint128` holds.
//!
//! `vectors/wire-vectors.json`'s `claim_voucher.evm` case is generated by
//! `connector-vectors` from this workspace's own EIP-712 code. That code
//! agreeing with itself proves nothing about x402; this test hands the
//! vector's `ChannelConfig` and amount to Base Sepolia's
//! `x402BatchSettlement` runtime bytecode, placed at its canonical address
//! on an `anvil` running as chain **84532** -- the vector's own chain id,
//! and the one its EIP-712 domain separator commits to -- and asserts the
//! contract answers the committed `channelId` and digest.

use connector_settlement::batch::EvmChannelConfig;
use connector_settlement_evm::test_support::x402::X402Chain;
use connector_settlement_evm::test_support::{require_anvil, Anvil};
use serde_json::Value;

/// This binary's own base port for [`Anvil::spawn_with_chain_id`], clear of
/// every other anvil binary's range.
const ANVIL_BASE_PORT: u16 = 22_900;

const WIRE_VECTORS: &str = include_str!("../../../vectors/wire-vectors.json");

fn bytes<const N: usize>(case: &Value, field: &str) -> [u8; N] {
    let text = case[field]
        .as_str()
        .unwrap_or_else(|| panic!("the vector's '{field}' is a hex string"));
    assert_eq!(text.len(), 2 * N, "'{field}' is {N} bytes of hex");
    let mut out = [0u8; N];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&text[2 * i..2 * i + 2], 16)
            .unwrap_or_else(|_| panic!("'{field}' is hex"));
    }
    out
}

/// Every EVM voucher case in the committed set.
const EVM_VOUCHER_CASES: [(&str, &str); 4] = [
    ("claim_voucher", "evm"),
    ("claim_voucher", "evm_above_u64_max"),
    ("peer_carriage", "voucher_evm"),
    ("payout_voucher", "evm"),
];

#[tokio::test]
async fn the_evm_voucher_vectors_are_what_the_deployed_contract_computes() {
    if !require_anvil() {
        return;
    }
    let vectors: Value = serde_json::from_str(WIRE_VECTORS).expect("the committed vectors parse");
    let anvil = Anvil::spawn_with_chain_id(ANVIL_BASE_PORT, 84_532).await;
    let x402 = X402Chain::place(&anvil.rpc_url).await;
    for (section, name) in EVM_VOUCHER_CASES {
        let case = &vectors[section][name];
        assert!(case.is_object(), "{section}.{name} is in the committed set");
        check_case(&x402, case, &format!("{section}.{name}")).await;
    }
}

async fn check_case(x402: &X402Chain, case: &Value, label: &str) {
    let chain_id = case["chain_id"]
        .as_u64()
        .expect("the vector names its chain");
    assert_eq!(
        chain_id, 84_532,
        "{label}: the vector is Base Sepolia's; if it moved, so must this test's chain"
    );
    let verifying_contract: [u8; 20] = bytes(case, "verifying_contract_hex");
    assert_eq!(
        verifying_contract,
        connector_signer::X402_BATCH_SETTLEMENT_ADDRESS,
        "{label}: the vector's verifying contract is the one this connector binds to"
    );
    assert_eq!(x402.chain_id(), chain_id);

    let config = &case["channel_config"];
    let config = EvmChannelConfig {
        payer: bytes(config, "payer_hex"),
        payer_authorizer: bytes(config, "payer_authorizer_hex"),
        receiver: bytes(config, "receiver_hex"),
        receiver_authorizer: bytes(config, "receiver_authorizer_hex"),
        token: bytes(config, "token_hex"),
        withdraw_delay: config["withdraw_delay"].as_u64().expect("a delay"),
        salt: bytes(config, "salt_hex"),
    };
    let channel_id: [u8; 32] = bytes(case, "channel_id_hex");
    assert_eq!(
        x402.contract_channel_id(&config).await,
        channel_id,
        "{label}: x402BatchSettlement.getChannelId(config) is the vector's channelId"
    );

    let amount: u128 = case["max_claimable_amount"]
        .as_str()
        .expect("the vector's amount is a decimal string (schema 8)")
        .parse()
        .expect("the vector's amount");
    let digest: [u8; 32] = bytes(case, "digest_hex");
    assert_eq!(
        x402.contract_voucher_digest(channel_id, amount).await,
        digest,
        "{label}: x402BatchSettlement.getVoucherDigest(channelId, amount) is the vector's digest"
    );
}
