/**
 * CLI Type Definitions
 *
 * Type definitions for the onboarding wizard and CLI commands.
 */

/**
 * Settlement preference options for the connector
 */
export type SettlementPreference = 'evm';

/**
 * Key management backend options
 */
export type KeyBackend = 'env' | 'aws-kms' | 'gcp-kms' | 'azure-kv';

/**
 * Log level options
 */
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

/**
 * Configuration generated by the onboarding wizard
 */
export interface OnboardingConfig {
  /** Unique identifier for this connector node */
  nodeId: string;

  /** Settlement preference: EVM only */
  settlementPreference: SettlementPreference;

  /** Ethereum address for EVM settlement */
  evmAddress?: string;

  /** Key management backend selection */
  keyBackend: KeyBackend;

  /** Whether to enable Prometheus/Grafana monitoring */
  enableMonitoring: boolean;

  /** BTP server port */
  btpPort: number;

  /** Health check and metrics HTTP port */
  healthCheckPort: number;

  /** Logging level */
  logLevel: LogLevel;
}

/**
 * Wizard prompt answers from inquirer
 */
export interface WizardAnswers {
  nodeId: string;
  settlementPreference: SettlementPreference;
  evmAddress?: string;
  keyBackend: KeyBackend;
  enableMonitoring: boolean;
  btpPort: number;
  healthCheckPort: number;
  logLevel: LogLevel;
}

/**
 * Result of .env file generation
 */
export interface EnvFileResult {
  /** Path where the .env file was written */
  path: string;

  /** Whether the file was successfully written */
  success: boolean;

  /** Error message if write failed */
  error?: string;
}

/**
 * Health check response structure
 */
export interface HealthCheckResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  version?: string;
  uptime?: number;
  dependencies?: Record<string, { status: string; latencyMs?: number }>;
}
