#!/usr/bin/env bash
# local/anyone -- a paid packet from the toon CLIENT to a connector reachable
# only at a `.anyone` hidden service.
#
#   ./local/anyone/run.sh up      build the daemon image, bring it up, render the config
#   ./local/anyone/run.sh pay     run the payer INSIDE the isolated network
#   ./local/anyone/run.sh verify  up + pay + down, as a gate would run it
#   ./local/anyone/run.sh down    tear it down, volumes included
#
# TOON_CLIENT_REPO must point at a toon-protocol/toon-client checkout with
# `pnpm build` already run: the payer is that repository's library, not
# `connector send`.
#
# Deliberately NOT wired into the Makefile or local/keys.sh. This topology
# rehearses the CLIENT EDGE against a second repository's build, so it cannot be
# a CI gate here the way `local/onion` cannot -- and it needs a daemon image
# that must be built rather than pulled. `local/README.md` says why at length.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
KEYS="$ROOT/local/.keys/anyone/connector"
TOON_CLIENT_REPO="${TOON_CLIENT_REPO:-$(cd "$ROOT/../toon-client" 2>/dev/null && pwd || true)}"

export HOST_UID="$(id -u)" HOST_GID="$(id -g)"

dc() {
  docker compose -f "$ROOT/docker-compose.yml" -f "$ROOT/local/anyone/compose.yml" \
    --profile evm --profile anyone "$@"
}

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "ERROR: $1 is required. $2" >&2; exit 1; }
}

# ── The keys, and the one that is NOT random ────────────────────────────────
# `signer.key` is random: it is this node's edge identity for the run and
# nothing outside the run refers to it. `settlement.key` is anvil account 3 --
# it must be an account the local chain funded, because the connector reads
# chain state through it. The payer is account 0, which is the one anvil's
# default mnemonic funds with mock USDC.
#
# THAT LITERAL IS PUBLIC and every local chain ships with it -- it is anvil's
# well-known default mnemonic, the same class of value `docker-compose.yml`
# already writes in the clear for the faucet's ETH_PRIVATE_KEY and
# TOKEN_PRIVATE_KEY. It is fine here and nowhere else. The generated files it
# lands in are written to `local/.keys/`, which is gitignored (ADR 0012), so
# nothing key-shaped is ever tracked.
#
# Mode 0644, not 0600: the image runs as uid 10001 and has to read these. They
# are throwaway local-chain keys and `local/.keys/` is gitignored (ADR 0012).
provision_keys() {
  mkdir -p "$KEYS"
  if [[ ! -f "$KEYS/signer.key" ]]; then
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' >"$KEYS/signer.key"
  fi
  printf '%s' '7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6' \
    >"$KEYS/settlement.key"
  chmod 644 "$KEYS"/*.key
}

case "${1:-up}" in
up)
  need docker "The address this topology needs is generated by a container."

  # ── Phase 1: the address does not exist until the daemon has run ──────────
  # The connector's config names an address only anon-b can generate, so the
  # daemon must start first. This is the one step nothing in this repository
  # can do for you on a real box either (ADR 0070 decision 7) -- here `run.sh`
  # plays the operator who copies it down.
  echo "--- starting the daemons and the chain (the address does not exist yet)"
  dc up -d --build anon-a anon-b anvil

  echo "--- waiting for bootstrap and for the address to be generated"
  addr=""
  for _ in $(seq 1 90); do
    addr="$(docker exec "$(dc ps -q anon-b)" \
      sh -c 'cat /var/lib/anon/hidden_service/hostname 2>/dev/null' 2>/dev/null | tr -d '\r\n' || true)"
    b="$(docker exec "$(dc ps -q anon-b)" \
      sh -c 'grep -c "Bootstrapped 100%" /var/lib/anon/notice.log 2>/dev/null' 2>/dev/null || echo 0)"
    a="$(docker exec "$(dc ps -q anon-a)" \
      sh -c 'grep -c "Bootstrapped 100%" /var/lib/anon/notice.log 2>/dev/null' 2>/dev/null || echo 0)"
    [[ -n "$addr" && "$b" != 0 && "$a" != 0 ]] && break
    sleep 10
  done

  if [[ ! "$addr" =~ ^[a-z2-7]{56}\.anyone$ ]]; then
    echo "ERROR: anon-b has not produced a v3 .anyone address." >&2
    echo "       Got: '${addr:-<nothing>}'" >&2
    echo "       An address ending in .onion means the image is anon v0.4.9.7 --" >&2
    echo "       this topology needs v0.4.10.2, which local/anon-image builds. A daemon" >&2
    echo "       that exited immediately usually means AgreeToTerms is missing." >&2
    echo "       'docker compose logs anon-b' says which." >&2
    exit 1
  fi
  echo "--- the connector is reachable at $addr"

  # ── Phase 2: the operator writes the address down ─────────────────────────
  # The connector never reads the daemon's hostname file and never speaks its
  # control protocol (ADR 0070 decision 7).
  provision_keys
  sed "s|placeholderplaceholderplaceholderplaceholderplaceholderb\.anyone|$addr|g" \
    "$HERE/connector.toml" >"$KEYS/.connector.toml.tmp"
  mv "$KEYS/.connector.toml.tmp" "$KEYS/connector.toml"
  chmod 644 "$KEYS/connector.toml"

  dc up -d --wait stub-app connector
  echo "--- up. The connector publishes no host port; the circuit is the only way in."
  ;;

pay)
  [[ -n "$TOON_CLIENT_REPO" && -d "$TOON_CLIENT_REPO/packages/client/dist" ]] || {
    echo "ERROR: TOON_CLIENT_REPO must name a toon-client checkout with 'pnpm build' run." >&2
    echo "       Looked for: ${TOON_CLIENT_REPO:-<unset>}/packages/client/dist" >&2
    exit 1; }

  addr="$(sed -n 's|^http_endpoint = "http://\([a-z2-7]*\.anyone\)/ilp"$|\1|p' \
    "$KEYS/connector.toml" | head -1)"
  [[ -n "$addr" ]] || { echo "ERROR: the rendered config names no .anyone endpoint; run 'up' first." >&2; exit 1; }

  mkdir -p "$HERE/.store"
  # On anyone-payer, which has no route and no DNS to the connector -- so
  # whatever this reaches, it reached over a circuit.
  docker run --rm --network "$(basename "$ROOT")_anyone-payer" \
    -v "$TOON_CLIENT_REPO:/repo:ro" \
    -v "$HERE:/work" \
    -e HS_ADDR="$addr" -e STORE=/work/.store \
    node:22-alpine node /work/pay.mjs
  ;;

verify)
  "$0" up
  status=0
  "$0" pay || status=$?
  if [[ $status -ne 0 ]]; then
    echo "--- rehearsal FAILED; logs follow ---" >&2
    dc logs --no-color --tail 40 connector anon-a anon-b >&2 || true
  fi
  "$0" down
  exit $status
  ;;

down)
  dc down -v --remove-orphans
  # The payer's channel store goes with them, and that is not tidiness. `-v`
  # takes anvil's chain and the connector's claim watermark with it; a store
  # left behind would sign the next run's claims against a channel that no
  # longer exists, at a nonce the fresh connector has never seen -- and the
  # rehearsal would fail as a replay, for a reason that looks like a bug. Same
  # argument as `local-down`'s `-v`.
  rm -f "$HERE/.store/channels.json"
  ;;

*)
  echo "usage: $0 {up|pay|verify|down}" >&2
  exit 1
  ;;
esac
